horizon_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path("auth/", include("django.contrib.auth.urls")),  
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.HomeView.as_view(), name='home'),
   path('auth/signup/', views.SignUpView.as_view(), name='sign-up'),
   
   path('visits/all/', views.VisitListView.as_view(), name='visit-list'),
   path('visits/<int:pk>/', views.VisitDetailView.as_view(), name='visit-details'),
   path('visits/create/', views.VisitCreateView.as_view(), name='visit-create'),
   path('visits/<int:pk>/edit/', views.VisistUpdateView.as_view(), name='visit-update'),
   path('visits/<int:pk>/delete/', views.VisitDeleteView.as_view(), name='visit-delete'),
   
   path('comments/all/', views.CommentListView.as_view(), name='comment-list'),
   path('visits/<int:visit_id>/comments/add/', views.CommentCreateView.as_view(), name='comment-create'),
   path('comments/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='comment-delete'),
   
   path('visits/<int:pk>/like/', views.ToggleVisitLike.as_view(), name='toggle_visit_like'),
   path('visits/<int:pk>/like/feed/', views.ToggleVisitLikeFeed.as_view(), name='toggle_visit_like_feed'),
   path('comments/<int:pk>/like/', views.ToggleCommentLike.as_view(), name='toggle_comment_like'),
   
   path('users/<int:pk>/', views.UserDetailView.as_view(), name='user-details'),
   path('users/<int:pk>/edit', views.UserUpdateView.as_view(), name='user-update'),
   path('user/changePassword/', views.UserChangePassword.as_view(), name='user-change-password'),
   path('users/<int:pk>/delete/', views.UserDeleteView.as_view(), name='user-delete'),
   path('users/<int:pk>/followers/', views.FollowersListView.as_view(), name='followers'),
   path('users/<int:pk>/following/', views.FollowingListView.as_view(), name='following'),
   path('users/<int:pk>/follow/', views.ToggleFollow.as_view(), name='toggle-follow'),
   path('users/<int:pk>/liked-visits/', views.UserLikedVisitsView.as_view(), name='user-liked-visits'),
   
   path('country/<int:pk>/', views.CountryDetailView.as_view(), name='country-details'),
   
   path('search/', views.Search.as_view(), name='search'),
   
   path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary_storage.storage import MediaCloudinaryStorage


# Create your models here.

class Country(models.Model):
    country_name = models.CharField(max_length=50, unique=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    
    class Meta:
        db_table = 'countries'
    
    def __str__(self):
        return self.country_name
    

class City(models.Model):
    country = models.ForeignKey(Country,on_delete=models.CASCADE)
    city_name = models.CharField(max_length=40)
    
    class Meta:
        db_table = 'city'
    
    def __str__(self):
        return self.city_name

    
class Visit(models.Model):
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(storage=MediaCloudinaryStorage())
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='visits')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='visits', null=True) 
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)   
    
    class Meta:
        db_table = 'visits'
    
    def __str__(self):
        return self.content
    
    

class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    visit = models.ForeignKey(Visit, on_delete= models.CASCADE, related_name='comments')
    
    class Meta:
        db_table = 'comments'
    
    def __str__(self):
        return self.content
    
    
    
class CommentLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comment_likes')
    comment = models.ForeignKey(Comment, on_delete= models.CASCADE, related_name='likes')
    
    class Meta:
        db_table = 'comment_likes'
    
    def __str__(self):
        return f'{self.user.username} liked {self.comment}'
    

class VisitLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='visit_likes')
    visit = models.ForeignKey(Visit, on_delete= models.CASCADE, related_name='likes')
    
    class Meta:
        db_table = 'visit_likes'
    
    def __str__(self):
        return f'{self.user.username} liked {self.visit}'
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(storage=MediaCloudinaryStorage(),blank=True, null=True)
    bio = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        db_table = 'profile'
    
    def __str__(self):
        return f"{self.user.username} Profile"
    
    
class Follow(models.Model):
    follower = models.ForeignKey(User, on_delete= models.CASCADE, related_name='following')
    following = models.ForeignKey(User, on_delete= models.CASCADE, related_name='followers')
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'follow'
        unique_together = ('follower', 'following') 
    
    def __str__(self):
        return f'{self.follower.username} follows {self.following.username}'
    

main_app/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from .models import City, Visit, Comment, VisitLike, CommentLike, Country, Follow
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from main_app.forms import SignupForm, VisitForm , CommentForm, UserUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.db.models import Q

# Create your views here.

class HomeView(TemplateView):
    template_name = 'home.html'


class SignUpView(CreateView):
    form_class = SignupForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("login")


class VisitListView(LoginRequiredMixin,ListView):
    model = Visit
    template_name = 'visit/visit-list.html'
    context_object_name = 'visits'
    
    def get_queryset(self):
        return Visit.objects.all().order_by('-created_at')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context['liked_visits'] = set(VisitLike.objects.filter(user=user).values_list('visit_id', flat=True))
        context['user_following'] = set(Follow.objects.filter(follower=user).values_list('following_id', flat=True))
        return context


class VisitDetailView(LoginRequiredMixin,DetailView):
    model = Visit
    template_name = 'visit/visit-details.html'
    context_object_name = 'visit'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        comments = self.object.comments.all().order_by('-created_at')
        context['comments'] = comments
        context['liked_visits'] = set(VisitLike.objects.filter(user=user).values_list('visit_id', flat=True))
        context['user_following'] = set(Follow.objects.filter(follower=user).values_list('following_id', flat=True))
        
        if user.is_authenticated:
            context['did_like_visit'] = VisitLike.objects.filter(user=user, visit=self.object).exists()

            for comment in comments:
                comment.did_like = CommentLike.objects.filter(user=user, comment=comment).exists()
        else:
            context['did_like_visit'] = False

            for comment in comments:
                comment.did_like = False

        return context


class VisitCreateView(LoginRequiredMixin, CreateView):
    model = Visit
    template_name = 'visit/visit-form.html'
    form_class = VisitForm
    
    def get_success_url(self):
        return reverse('visit-list')


    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class VisistUpdateView(LoginRequiredMixin,UpdateView):
    model = Visit
    template_name = 'visit/visit-form.html'
    form_class = VisitForm
    context_object_name = 'visit'

    def get_success_url(self):
        return reverse('visit-list')


class VisitDeleteView(LoginRequiredMixin,DeleteView):
    model = Visit
    context_object_name = 'visit'
    
    def get_success_url(self):
        return reverse('visit-list')


class CommentListView(LoginRequiredMixin,ListView):
    model = Comment
    template_name = 'comment/comment-list.html'
    context_object_name = 'comments'


class CommentCreateView(LoginRequiredMixin,CreateView):
    model = Comment
    template_name = 'comment/comment-form.html'
    form_class = CommentForm
    
    def get_success_url(self):
        return reverse('visit-details', kwargs={'pk': self.kwargs['visit_id']})

    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.visit = Visit.objects.get(pk=self.kwargs.get('visit_id'))
        return super().form_valid(form)


class CommentDeleteView(LoginRequiredMixin,DeleteView):
    model = Comment
    context_object_name = "comment"
    
    def get_success_url(self):
        return reverse("visit-details", kwargs={"pk": self.object.visit.id})
    
    def get_queryset(self):
        return Comment.objects.filter(user=self.request.user)


class ToggleVisitLike(LoginRequiredMixin, View):
    def post(self, request, pk):
        visit = Visit.objects.get(pk=pk)
        like, created = VisitLike.objects.get_or_create(user=request.user, visit=visit)
        if not created: 
            like.delete()
            liked = False
        else:
            liked = True
    
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':     
            data = {
                'liked': liked,
                'count': visit.likes.count(),
                }
            return JsonResponse(data)
            
        return redirect('visit-details', pk=visit.pk) 



class ToggleVisitLikeFeed(LoginRequiredMixin, View):
    def post(self, request, pk):
        visit = Visit.objects.get(pk=pk)
        like, created = VisitLike.objects.get_or_create(user=request.user, visit=visit)
        if not created: 
            like.delete()
            liked = False
        else:
            liked = True
    
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':     
            data = {
                'liked': liked,
                'count': visit.likes.count(),
                }
            return JsonResponse(data)
            
        return redirect('visit-list') 


class ToggleCommentLike(LoginRequiredMixin, View):
    def post(self, request, pk):
        comment = Comment.objects.get(pk=pk)
        like, created = CommentLike.objects.get_or_create(user=request.user, comment=comment)
        if not created:  
            like.delete()
            liked = False
        else:
            liked = True
        
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            data = {
            'liked': liked,
            'count': comment.likes.count(),
            }
            return JsonResponse(data)
            
        return redirect('visit-details', pk=comment.visit.pk)


class UserDetailView(LoginRequiredMixin,DetailView):
    model = User
    template_name = 'user/user-profile.html'
    context_object_name = 'user'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["visits"] = self.object.visits.all().order_by('-created_at')
        context["followers_count"] = Follow.objects.filter(following=self.object).count()
        context["following_count"] = Follow.objects.filter(follower=self.object).count()
        context["posts_count"] = self.object.visits.count()
        
        if self.request.user.is_authenticated and self.request.user != self.object:
            context["is_following"] = Follow.objects.filter(follower=self.request.user, following=self.object).exists()
        else:
            context["is_following"] = False   
        
        return context


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user/user-update.html'
    form_class = UserUpdateForm

    def test_func(self):
        return self.request.user == self.get_object()

    def get_success_url(self):
        return reverse_lazy("user-details", kwargs={"pk": self.object.id})


class UserChangePassword(UserPassesTestMixin, PasswordChangeView):
    template_name = 'user/user-change-password.html'
    
    def test_func(self):
        return self.request.user
    
    def get_success_url(self):
        return reverse_lazy("user-details", kwargs={"pk": self.request.user.pk})


class UserDeleteView(UserPassesTestMixin, DeleteView):
    model = User
    template_name = 'user/user-confirm-delete.html'
    success_url = reverse_lazy('sign-up')
    
    def test_func(self):
        return self.request.user == self.get_object()


class CountryDetailView(LoginRequiredMixin,DetailView):
    model = Country
    template_name = 'country/country-details.html'
    context_object_name = 'country'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['visits'] = self.get_object().visits.all().order_by('-created_at') 
        return context 


class Search(LoginRequiredMixin,TemplateView):
    template_name = 'search.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        query_request = self.request.GET.get('q', None)
        
        if query_request is None:
            query = ""
        else:
            query = query_request.strip()
            
        users = User.objects.none()
        countries = Country.objects.none()
        
        if query != "":
            user_filter = (
                Q(username__icontains=query) |
                Q(first_name__icontains=query) |
                Q(last_name__icontains=query)
            )
            users = User.objects.filter(user_filter)
            
            country_filter = Q(country_name__icontains=query)
            countries = Country.objects.filter(country_filter)
        
        context['query'] = query
        context['users'] = users
        context['countries'] = countries
        
        return context


def load_cities(request):
    country_id = request.GET.get('country')
    cities = City.objects.filter(country_id=country_id).order_by('city_name')
    return render(request, 'city/city_dropdown_list_options.html', {'cities': cities})


class FollowersListView(LoginRequiredMixin,ListView):
    model = Follow
    template_name = 'follow/followrs-list.html'
    context_object_name = 'followers'
    
    def get_queryset(self):
        return Follow.objects.filter(following_id= self.kwargs['pk'])
    
    def get_context_data(self, **kwargs):

main_app/templates/visit/visit-details.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link rel="stylesheet" href="{% static 'styles/visit/visit-details.css' %}">
{% endblock head %}

{% block body %}
<div class="content">
    <div class="visit-card">
        <div class="user-info">
            <a href="{% url 'user-details' visit.user.pk %}">
                {% if visit.user.profile.profile_photo %}
                    <img src="{{ visit.user.profile.profile_photo.url }}" alt="{{ visit.user.username }}">
                {% else %}
                    <img src="https://res.cloudinary.com/dquu356xs/image/upload/v1757511943/no-pfp_sx5tta.webp" alt="Default Profile">
                {% endif %}
            </a>
            <div class="user-name-time-edit">
                <div class="user-name-block">
                    <div class="username-follow">
                        <a href="{% url 'user-details' visit.user.pk %}" class="username">{{ visit.user.username }}</a>
                        
                        {% if request.user != visit.user %}
                            <form method="post" action="{% url 'toggle-follow' visit.user.pk %}" class="follow-form" data-user="{{ visit.user.pk }}">
                                {% csrf_token %}
                                <button type="submit" class="follow-btn{{ visit.user.pk }}">
                                    {% if visit.user.pk in user_following %}
                                        • <span class="follow-text{{ visit.user.pk }}">Following</span>
                                    {% else %}
                                        • <span class="follow-text{{ visit.user.pk }}">Follow</span>
                                    {% endif %}
                                </button>
                            </form>
                        {% endif %}
                    </div>
                    <p class="visit-posted">{{ visit.created_at|timesince }} ago</p>
                </div>
                {% if user == visit.user %}
                <div class="edit-delete-btns">
                    <a href="{% url 'visit-update' visit.pk %}"><i class="fa-solid fa-pencil"></i></a>
                    <form method="post" action="{% url 'visit-delete' visit.pk %}">
                        {% csrf_token %}
                        <button type="submit"><i class="fa-solid fa-trash"></i></button>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
        {% if visit.photo %}
        <div class="visit-photo">
            <img src="{{ visit.photo.url }}" alt="Visit photo">
        </div>
        {% endif %}
        <div class="like-section">
            <form method="post" action="{% url 'toggle_visit_like' visit.pk %}" class="like-form" id="{{ visit.pk }}">
                {% csrf_token %}
                <button type="submit" class="like-btn{{ visit.pk }}">
                    {% if visit.pk in liked_visits %}
                        <span class="like-count{{ visit.pk }}">♥ {{ visit.likes.count }}</span>
                    {% else %}
                        <span class="like-count{{ visit.pk }}">♡ {{ visit.likes.count }}</span>
                    {% endif %}
                </button>
            </form>
            <a href="{% url 'visit-details' visit.pk %}" class="comment-btn">
                <i class="fa-regular fa-comment"></i> <span class="comment-count">{{ visit.comments.count }}</span>
            </a>
        </div>
        <a href="{% url 'country-details' visit.country.pk %}" class="location">
            <strong>{{ visit.city.city_name }}</strong> {{ visit.country.country_name }}
        </a>
        {% if visit.content %}
        <p class="visit-content">{{ visit.content }}</p>
        {% endif %}
        <p class="visit-dates">Visted on {{ visit.start_date.date }} - {{ visit.end_date.date|default:"N/A" }}</p>

        <div class="comments-section">
            <h2>Comments</h2>
            {% for comment in comments %}
                <div class="comment">
                    <div class="comment-header">
                        <div class="comment-user-left">
                            <a href="{% url 'user-details' comment.user.pk %}">
                                {% if comment.user.profile.profile_photo %}
                                    <img src="{{ comment.user.profile.profile_photo.url }}" alt="{{ comment.user.username }}">
                                {% else %}
                                    <img src="https://res.cloudinary.com/dquu356xs/image/upload/v1757511943/no-pfp_sx5tta.webp" alt="Default Profile">
                                {% endif %}
                            </a>
                            <div class="comment-username">
                                <a href="{% url 'user-details' comment.user.pk %}">{{ comment.user.username }}</a>
                            </div>
                            <div class="comment-date">{{ comment.created_at|timesince }} ago</div>
                        </div>
                        <div class="comment-actions">
                            <form method="post" action="{% url 'toggle_comment_like' comment.pk %}" class="comment-like-form" id="{{ comment.pk }}">
                                {% csrf_token %}
                                <button type="submit" class="comment-like-btn{{ comment.pk }}">
                                    {% if comment.did_like %}
                                        <span class="comment-like-count">♥ {{ comment.likes.count }}</span>
                                    {% else %}
                                        <span class="comment-like-count">♡ {{ comment.likes.count }}</span>
                                    {% endif %}
                                </button>
                            </form>
                            {% if user == comment.user %}
                                <form method="post" action="{% url 'comment-delete' comment.pk %}">
                                    {% csrf_token %}
                                    <button type="submit"><i class="fa-solid fa-trash"></i></button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                    <div class="comment-content">{{ comment.content }}</div>
                </div>
            {% empty %}
                <p>Start the conversation</p>
            {% endfor %}
        </div>
            {% if user.is_authenticated %}
                <div class="add-comment-form">
                    <form method="post" action="{% url 'comment-create' visit.pk %}">
                        {% csrf_token %}
                        <textarea id="content" name="content" placeholder="Write a comment..." required></textarea>
                        <button type="submit" class="action-btn">Comment</button>
                    </form>
                </div>
            {% else %}
                <p>Log in to comment</p>
            {% endif %}
    </div>
</div>
{% endblock body %}
{% block scripts %} 
<script>
$(document).ready(function() {
    let display = false
    $(".cmt_btn").click(function() {
        if (display === false) {
            $(this).next(".comment-box").show("slow")
            display = true
        } else {
            $(this).next(".comment-box").hide("slow")
            display = false
        }
    })

    $('.like-form').submit(function(e){
        e.preventDefault()

        const post_id = $(this).attr('id')
        const likeText = $(`.like-btn${post_id}`).text()
        const trim = $.trim(likeText)
        const url = $(this).attr('action')

        let res
        const likes = $(`.like-count${post_id}`).text()
        const trimCount = parseInt(likes)

        $.ajax({
            type: 'POST',
            url: url,
            data: {
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                'post_id': post_id,
            },
            success: function(response) {
                if(!response.liked) {
                    $(`.like-btn${post_id}`).html(`<span class="like-count${post_id}">♡ ${response.count}</span>`)
                } else {
                    $(`.like-btn${post_id}`).html(`<span class="like-count${post_id}">♥ ${response.count}</span>`)
                }
            },
            error: function(response) {
                console.log('error', response)
            }
        })
    })

    $('.comment-like-form').submit(function(e){
        e.preventDefault()

        const comment_id = $(this).attr('id')
        const likeText = $(`.comment-like-btn${comment_id}`).text()
        const trim = $.trim(likeText)
        const url = $(this).attr('action')

        let res
        const likes = $(`.comment-like-count${comment_id}`).text()
        const trimCount = parseInt(likes)

        $.ajax({
            type: 'POST',
            url: url,
            data: {
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                'comment_id': comment_id,
            },
            success: function(response) {
                if(trim.includes('♥')) {
                    $(`.comment-like-btn${comment_id}`).html(`<span class="comment-like-count${comment_id}">♡ ${response.count}</span>`)
                } else {
                    $(`.comment-like-btn${comment_id}`).html(`<span class="comment-like-count${comment_id}">♥ ${response.count}</span>`)
                }
            },
            error: function(response) {
                console.log('error', response)
            }
        })
    })

    $('.follow-form').submit(function(e){
        e.preventDefault()

        const user_id = $(this).data('user')
        const url = $(this).attr('action')

        $.ajax({
            type: 'POST',
            url: url,
            data: {
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function(response){
                if(response.followed){
                    $(`.follow-text${user_id}`).text('Following')
                } else {
                    $(`.follow-text${user_id}`).text('Follow')
                }
            },
            error: function(response){
                console.log('error', response)
            }
        })
    })
})
</script>
{% endblock scripts %}

main_app/templates/visit/visit-form.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="{% static 'styles/visit/visit-form.css' %}">
{% endblock head %}

{% block body %}
<div class="content">
  <div class="visit-card">

  {% if visit %}
    <h1 class="form-title">Edit Post</h1>
  {% else %}
    <h1 class="form-title">New Post</h1>
  {% endif %}

    <form method="post" enctype="multipart/form-data" id="VisitForm" data-cities-url="{% url 'ajax_load_cities' %}" class="visit-form">
    {% csrf_token %}

    <label for="photo">Photo</label>
    <input value="{{visit.photo}}" type="file" name="photo" id="photo" accept="image/*" required>
    
    <label for="country">Country</label>
        {{ form.country }}

    <label for="city_name">City</label>
        {{form.city}}

    <label for="start_date">Start Date</label>
    <input value="{{ visit.start_date|date:'Y-m-d' }}" type="date" name="start_date" id="start_date" required>

    <label for="end_date">End Date</label>
    <input value="{{ visit.end_date|date:'Y-m-d' }}" type="date" name="end_date" id="end_date">

    <label for="content">Caption</label>
    <textarea name="content" id="content" rows="4">{{visit.content}}</textarea>

      
      <div class="visit-form-actions">
        {% if visit %}
          <button  class="visit-save-btn" type="submit">Save</button>
          <a href="{% url "visit-details" visit.pk %}" class="visit-back-btn">Back</a>
        {% else %}
          <button class="visit-save-btn" type="submit">Post</button>
          <a href="{% url "visit-list" %}" class="visit-back-btn">Back</a>
        {% endif %}
      </div>

  </form>
</div>
</div>

{% endblock body %}

{% block scripts %}

  <script>
      $("#id_country").change(function () {
        var url = $("#VisitForm").attr("data-cities-url") 
        var countryId = $(this).val()                        

      $.ajax({  
          url: url,
          data: {
             'country': countryId
          },
          success: function (data) {
            $("#id_city").html(data)
          }
     })
    })
  </script>

{% endblock scripts %}